In [8]:
# Initialize the random number generator
rng = MersenneTwister();

In [9]:
# Size of the matrix
n = 512;

In [10]:
# Random initialization of matrix A
L = zeros(Float64,n,n)
U = zeros(Float64,n,n)
for i=1:n
    L[i,i] = 1
    L[i+1:n,i] = rand(rng, -2:2, n-i)
    U[i,i] = rand(rng, 1:2)
    U[i,i+1:n] = rand(rng, -2:2, n-i)
end
A = L * U
A0 = copy(A);
A0[1:6,1:6]

6x6 Array{Float64,2}:
  1.0  -1.0  -2.0   2.0   2.0  -2.0
 -2.0   4.0   4.0  -3.0  -6.0   2.0
 -1.0   5.0   4.0  -1.0  -4.0   0.0
  2.0  -4.0  -4.0   4.0   7.0  -2.0
  0.0  -4.0   2.0  -1.0  10.0   7.0
  2.0   2.0   0.0   3.0   7.0  -1.0

In [11]:
# Initializing the right-hand side
xe = rand(rng, 0:9, n) # This will be our solution
b = A * xe
b'

1x512 Array{Float64,2}:
 48.0  -188.0  -288.0  392.0  551.0  …  -2369.0  -2213.0  1989.0  -1777.0

In [12]:
include("getrf.jl")

getrs (generic function with 3 methods)

In [13]:
# Test our solvers
map([getrfOuter!, getrfAxpy!, getrfDot!]) do solver
    A = copy(A0)
    solver(A)
    # Solve
    x = getrs(A, b)
    @assert x == xe
    println(string(solver) * ": PASSED")
end    

getrfOuter!: PASSED
getrfAxpy!: PASSED
getrfDot!: PASSED


3-element Array{Void,1}:
 nothing
 nothing
 nothing

In [14]:
# Time the solvers
map([getrfOuter!, getrfAxpy!, getrfDot!]) do solver
    A = copy(A0); @time solver(A)
end

  0.151760 seconds (4 allocations: 160 bytes, 4.54% gc time)
  0.093780 seconds (4 allocations: 160 bytes)
  0.146238 seconds (4 allocations: 160 bytes)


3-element Array{Void,1}:
 nothing
 nothing
 nothing